### ISSUE TITLE
Homebridge 2.0 issue

### ISSUE THREAD

**Issue by xhanjiv** [johnlemonse/homebridge-telldus#106]
Getting the following after upgrading to Homebride v2.0.0-beta.21:
TypeError: Assignment to constant variable.
    at new TelldusPlatform (/homebridge/node_modules/@pontusnilsson/homebridge-telldus-pn/index.js:98:8)
    at file:///homebridge/node_modules/homebridge/src/server.ts:459:40
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (file:///homebridge/node_modules/homebridge/src/server.ts:386:27)
    at Server.start (file:///homebridge/node_modules/homebridge/src/server.ts:167:29)
[9/15/2024, 9:49:52 AM] Got SIGTERM, shutting down Homebridge...
[9/15/2024, 9:49:52 AM] AssertionError [ERR_ASSERTION]: Cannot generate setupURI on an accessory that isn't published yet!
    at Bridge.setupURI (/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:897:11)
    at Server.setServerStatus (file:///homebridge/node_modules/homebridge/src/server.ts:146:45)
    at Server.teardown (file:///homebridge/node_modules/homebridge/src/server.ts:190:10)
    at signalHandler (file:///homebridge/node_modules/homebridge/src/cli.ts:94:12)
    at process.emit (node:events:519:28)
    at process.emit (/homebridge/node_modules/homebridge/node_modules/source-map-support/source-map-support.js:516:21)
[9/15/2024, 9:50:03 AM] [Telldus] Initializing Telldus platform...

My Telldus config looks like this:
{
    "platform": "Telldus",
    "name": "Telldus Liv!e",
    "local": {
        "ip_address": "192.168..xx.yy",
        "access_token": "my access token here"
    },
    "unknown_accessories": [
        {
            "local_id": 3,
            "model": "switch",
            "protocol": "zwave",
            "type": "device",
            "disabled": "true"
        },
        {
            "local_id": 29,
            "model": "switch",
            "protocol": "zwave",
            "type": "device",
            "disabled": "true"
        }
    ]
}

**Comment by xhanjiv** [comment]
More complete error:
[9/15/2024, 11:29:56 AM] [Telldus Liv!e] Initializing Telldus platform...
[9/15/2024, 11:29:56 AM] [Telldus Liv!e] isLocal: true
[9/15/2024, 11:29:56 AM] TypeError: Assignment to constant variable.
    at new TelldusPlatform (/homebridge/node_modules/@pontusnilsson/homebridge-telldus-pn/index.js:98:8)
    at file:///homebridge/node_modules/homebridge/src/server.ts:459:40
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (file:///homebridge/node_modules/homebridge/src/server.ts:386:27)
    at Server.start (file:///homebridge/node_modules/homebridge/src/server.ts:167:29)
[9/15/2024, 11:29:56 AM] Got SIGTERM, shutting down Homebridge...
[9/15/2024, 11:29:56 AM] AssertionError [ERR_ASSERTION]: Cannot generate setupURI on an accessory that isn't published yet!
    at Bridge.setupURI (/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:897:11)
    at Server.setServerStatus (file:///homebridge/node_modules/homebridge/src/server.ts:146:45)
    at Server.teardown (file:///homebridge/node_modules/homebridge/src/server.ts:190:10)
    at signalHandler (file:///homebridge/node_modules/homebridge/src/cli.ts:94:12)
    at process.emit (node:events:519:28)
    at process.emit (/homebridge/node_modules/homebridge/node_modules/source-map-support/source-map-support.js:516:21)
[9/15/2024, 11:30:01 AM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null

**Comment by xhanjiv** [comment]
Sorry! Not an issue with homebridge-telldus at all.
