### ISSUE TITLE
Error loading plugin

### ISSUE THREAD

**Issue by claybeach** [johnlemonse/homebridge-telldus#68]
Hi,

I have a problem with Homebridge-Telldus plugin. It doesn't seems to work. As you can see down below it gives me an "error loading plugin". I have tried to re-install Homebridge-Telldus plugin and upgrae everything else, but can't still understand what is the issue.

Wish you could help me with this.

Best regards,
Tommi

pi@raspberrypi:~ $ homebridge
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see http://0pointer.de/avahi-compat?s=libdns_sd&e=node
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister
[2018-3-10 19:02:32] ====================
[2018-3-10 19:02:32] ERROR LOADING PLUGIN homebridge-telldus:
[2018-3-10 19:02:32] /usr/local/lib/node_modules/homebridge-telldus/node_modules/telldus-api/index.js:221
...oauth.toHeader(oauth.authorize(
^^^

SyntaxError: Unexpected token ...
at createScript (vm.js:74:10)
at Object.runInThisContext (vm.js:116:10)
at Module._compile (module.js:533:28)
at Object.Module._extensions..js (module.js:580:10)
at Module.load (module.js:503:32)
at tryModuleLoad (module.js:466:12)
at Function.Module._load (module.js:458:3)
at Module.require (module.js:513:17)
at require (internal/module.js:11:18)
at Object. (/usr/local/lib/node_modules/homebridge-telldus/index.js:6:31)
at Module._compile (module.js:569:30)
at Object.Module._extensions..js (module.js:580:10)
at Module.load (module.js:503:32)
at tryModuleLoad (module.js:466:12)
at Function.Module._load (module.js:458:3)
at Module.require (module.js:513:17)
[2018-3-10 19:02:32] ====================
[2018-3-10 19:02:32] No plugins found. See the README for information on installing plugins.
[2018-3-10 19:02:32] Loaded config.json with 0 accessories and 1 platforms.
[2018-3-10 19:02:32] ---
[2018-3-10 19:02:32] Loading 1 platforms...
/usr/local/lib/node_modules/homebridge/lib/api.js:122
throw new Error("The requested platform '" + name + "' was not registered by any plugin.");
^

Error: The requested platform 'Telldus' was not registered by any plugin.
at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:122:13)
at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:294:45)
at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:85:36)
at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
at Object. (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
at Module._compile (module.js:569:30)
at Object.Module._extensions..js (module.js:580:10)
at Module.load (module.js:503:32)
at tryModuleLoad (module.js:466:12)
at Function.Module._load (module.js:458:3)
at Function.Module.runMain (module.js:605:10)
at startup (bootstrap_node.js:158:16)
at bootstrap_node.js:575:3

**Comment by mifi** [comment]
I think you are running with a too old version of node.js. Requires node 8.3 or greater
