### ISSUE TITLE
Can not get Telldus to work

### ISSUE THREAD

**Issue by Mattiasfoto** [johnlemonse/homebridge-telldus#88]
I do not get Telldus to work in Home Bridge. I have tried a lot but nothing works for me.
I enclose part of my log file so maybe someone here can help.

**I have a Telldus Znet v2 and a Raspberry Pi4.**

[21/12/2020, 22:32:27] [HB Supervisor] Starting Homebridge with extra flags: -I
[21/12/2020, 22:32:27] [HB Supervisor] Started Homebridge v1.1.7 with PID: 1070
[21/12/2020, 22:32:28] Loaded config.json with 0 accessories and 2 platforms.
[21/12/2020, 22:32:28] ---
[21/12/2020, 22:32:29] Loaded plugin: homebridge-config-ui-x@4.36.0
[21/12/2020, 22:32:29] Registering platform 'homebridge-config-ui-x.config'
[21/12/2020, 22:32:29] ---
[21/12/2020, 22:32:29] Loaded plugin: homebridge-telldus@1.0.7
[21/12/2020, 22:32:29] Registering platform 'homebridge-telldus.Telldus'
[21/12/2020, 22:32:29] ---
[21/12/2020, 22:32:29] Loading 2 platforms...
[21/12/2020, 22:32:29] [Config] Initializing config platform...
[21/12/2020, 22:32:29] [Config] Running in Service Mode
[21/12/2020, 22:32:29] [Telldus Liv!e] Initializing Telldus platform...
[21/12/2020, 22:32:29] [Telldus Liv!e] isLocal: true
[21/12/2020, 22:32:29] [Telldus Liv!e] Loading accessories...
[21/12/2020, 22:32:29] [Telldus Liv!e] Found 7 sensors in telldus live.
[21/12/2020, 22:32:29] [Telldus Liv!e] Creating accessory with ID 25. Name from telldus: Utetemperatur
[21/12/2020, 22:32:29] [Telldus Liv!e] Creating accessory with ID 29. Name from telldus: Lejas taklampa
[21/12/2020, 22:32:29] [Telldus Liv!e] Creating accessory with ID 32. Name from telldus: Lampa köksfönster
[21/12/2020, 22:32:29] [Telldus Liv!e] Creating accessory with ID 38. Name from telldus: Ipad laddare
[21/12/2020, 22:32:29] [Telldus Liv!e] Creating accessory with ID 40. Name from telldus: TV bänk
[21/12/2020, 22:32:29] [Telldus Liv!e] Creating accessory with ID 41. Name from telldus: Vardagsrum spotlights
[21/12/2020, 22:32:29] [Telldus Liv!e] Creating accessory with ID 50. Name from telldus: Garage porten
[21/12/2020, 22:32:29] [Telldus Liv!e] Found 36 devices in telldus live.
[21/12/2020, 22:32:32] [Telldus Liv!e] Creating accessory with ID 4. Name from telldus: V.rum hylla
[21/12/2020, 22:32:32] [Telldus Liv!e] Creating accessory with ID 5. Name from telldus: Utebelysning fasad
[21/12/2020, 22:32:32] [Telldus Liv!e] Creating accessory with ID 6. Name from telldus: Tvbänk led
[21/12/2020, 22:32:32] [Telldus Liv!e] Creating accessory with ID 7. Name from telldus: Vattenpump
[21/12/2020, 22:32:32] [Telldus Liv!e] Creating accessory with ID 9. Name from telldus: Decklights entre
[21/12/2020, 22:32:32] [Telldus Liv!e] Creating accessory with ID 10. Name from telldus: Mattias sänglampa
[21/12/2020, 22:32:32] [Telldus Liv!e] Creating accessory with ID 11. Name from telldus: Lejas fönster
[21/12/2020, 22:32:32] [Telldus Liv!e] Creating accessory with ID 12. Name from telldus: Köks lampor
[21/12/2020, 22:32:32] [Telldus Liv!e] Creating accessory with ID 14. Name from telldus: Hall lampa
[21/12/2020, 22:32:32] [Telldus Liv!e] Creating accessory with ID 15. Name from telldus: Gästrum
[21/12/2020, 22:32:32] [Telldus Liv!e] Creating accessory with ID 16. Name from telldus: Garage spotlights
[21/12/2020, 22:32:32] [Telldus Liv!e] Creating accessory with ID 17. Name from telldus: Garage belysning
[21/12/2020, 22:32:32] [Telldus Liv!e] Creating accessory with ID 18. Name from telldus: Entretak grov
[21/12/2020, 22:32:32] [Telldus Liv!e] Creating accessory with ID 19. Name from telldus: Entretak fin
[21/12/2020, 22:32:32] [Telldus Liv!e] Creating accessory with ID 21. Name from telldus: Buttkickers
[21/12/2020, 22:32:32] [Telldus Liv!e] Creating accessory with ID 31. Name from telldus: Räcke ledstrip
[21/12/2020, 22:32:32] [Telldus Liv!e] Creating accessory with ID 39. Name from telldus: Vardagsrum
[21/12/2020, 22:32:32] [Telldus Liv!e] Creating accessory with ID 23. Name from telldus: Utebelysning
[21/12/2020, 22:32:32] [Telldus Liv!e] Creating accessory with ID 24. Name from telldus: Sova
[21/12/2020, 22:32:32] [Telldus Liv!e] Creating accessory with ID 33. Name from telldus: Verisure Alarm
[21/12/2020, 22:32:32] [Telldus Liv!e] Creating accessory with ID 27. Name from telldus: Nexa z-dimmer
[21/12/2020, 22:32:32] [Telldus Liv!e] Creating accessory with ID 29. Name from telldus: Lejas taklampa
[21/12/2020, 22:32:32] [Telldus Liv!e] Creating accessory with ID 32. Name from telldus: Lampa köksfönster
[21/12/2020, 22:32:32] [Telldus Liv!e] Creating accessory with ID 38. Name from telldus: Ipad laddare
[21/12/2020, 22:32:32] [Telldus Liv!e] Creating accessory with ID 40. Name from telldus: TV bänk
[21/12/2020, 22:32:32] [Telldus Liv!e] Creating accessory with ID 41. Name from telldus: Vardagsrum spotlights
[21/12/2020, 22:32:32] [Telldus Liv!e] Creating accessory with ID 50. Name from telldus: Garage porten
[21/12/2020, 22:32:32] [Telldus Liv!e] Creating accessory with ID 51. Name from telldus: 1
[21/12/2020, 22:32:32] [Telldus Liv!e] Creating accessory with ID 52. Name from telldus: 2
[21/12/2020, 22:32:32] [Telldus Liv!e] Creating accessory with ID 53. Name from telldus: 3
[21/12/2020, 22:32:32] [Telldus Liv!e] Creating accessory with ID 54. Name from telldus: 4
[21/12/2020, 22:32:32] [Telldus Liv!e] Creating accessory with ID 55. Name from telldus: Garage porten1
[21/12/2020, 22:32:32] [Telldus Liv!e] Creating accessory with ID 56. Name from telldus: 6
[21/12/2020, 22:32:32] [Telldus Liv!e] Creating accessory with ID 57. Name from telldus: 7
[21/12/2020, 22:32:32] [Telldus Liv!e] Creating accessory with ID 58. Name from telldus: Garage porten
[21/12/2020, 22:32:32] [Telldus Liv!e] Creating accessory with ID 59. Name from telldus: Julgranen
[21/12/2020, 22:32:32] Initializing platform accessory 'Utetemperatur'...
[21/12/2020, 22:32:32] Initializing platform accessory 'Lejas taklampa'...
[21/12/2020, 22:32:32] [Telldus Liv!e] [Lejas taklampa] Your device (model 0159-0001-0051, id 29) is not auto detected from telldus live. Please add the following to your config, under telldus platform (replace MODEL with a valid type, and optionally set manufacturer):
"unknown_accessories": [{ "id": 29, "model": "MODEL", "manufacturer": "unknown" }]
Valid models are: selflearning-switch, codeswitch, selflearning-dimmer, temperature, EA4C, temperaturehumidity, 1A2D, window-covering, switch
[21/12/2020, 22:32:32] Initializing platform accessory 'Lampa köksfönster'...
[21/12/2020, 22:32:32] [Telldus Liv!e] [Lampa köksfönster] Your device (model 0159-0001-0051, id 32) is not auto detected from telldus live. Please add the following to your config, under telldus platform (replace MODEL with a valid type, and optionally set manufacturer):
"unknown_accessories": [{ "id": 32, "model": "MODEL", "manufacturer": "unknown" }]
Valid models are: selflearning-switch, codeswitch, selflearning-dimmer, temperature, EA4C, temperaturehumidity, 1A2D, window-covering, switch
[21/12/2020, 22:32:32] Initializing platform accessory 'Ipad laddare'...
[21/12/2020, 22:32:32] [Telldus Liv!e] [Ipad laddare] Your device (model 0159-0002-0052, id 38) is not auto detected from telldus live. Please add the following to your config, under telldus platform (replace MODEL with a valid type, and optionally set manufacturer):
"unknown_accessories": [{ "id": 38, "model": "MODEL", "manufacturer": "unknown" }]
Valid models are: selflearning-switch, codeswitch, selflearning-dimmer, temperature, EA4C, temperaturehumidity, 1A2D, window-covering, switch
[21/12/2020, 22:32:32] Initializing platform accessory 'TV bänk'...
[21/12/2020, 22:32:32] [Telldus Liv!e] [TV bänk] Your device (model 010f-0602-1003, id 40) is not auto detected from telldus live. Please add the following to your config, under telldus platform (replace MODEL with a valid type, and optionally set manufacturer):
"unknown_accessories": [{ "id": 40, "model": "MODEL", "manufacturer": "unknown" }]
Valid models are: selflearning-switch, codeswitch, selflearning-dimmer, temperature, EA4C, temperaturehumidity, 1A2D, window-covering, switch
[21/12/2020, 22:32:32] Initializing platform accessory 'Vardagsrum spotlights'...
[21/12/2020, 22:32:32] [Telldus Liv!e] [Vardagsrum spotlights] Your device (model 0159-0001-0055, id 41) is not auto detected from telldus live. Please add the following to your config, under telldus platform (replace MODEL with a valid type, and optionally set manufacturer):
"unknown_accessories": [{ "id": 41, "model": "MODEL", "manufacturer": "unknown" }]
Valid models are: selflearning-switch, codeswitch, selflearning-dimmer, temperature, EA4C, temperaturehumidity, 1A2D, window-covering, switch
[21/12/2020, 22:32:32] Initializing platform accessory 'Garage porten'...
[21/12/2020, 22:32:32] [Telldus Liv!e] [Garage porten] Your device (model 010f-0502-1000, id 50) is not auto detected from telldus live. Please add the following to your config, under telldus platform (replace MODEL with a valid type, and optionally set manufacturer):
"unknown_accessories": [{ "id": 50, "model": "MODEL", "manufacturer": "unknown" }]
Valid models are: selflearning-switch, codeswitch, selflearning-dimmer, temperature, EA4C, temperaturehumidity, 1A2D, window-covering, switch
[21/12/2020, 22:32:32] Initializing platform accessory 'V.rum hylla'...
[21/12/2020, 22:32:32] Initializing platform accessory 'Utebelysning fasad'...
[21/12/2020, 22:32:32] Initializing platform accessory 'Tvbänk led'...
[21/12/2020, 22:32:32] Initializing platform accessory 'Vattenpump'...
[21/12/2020, 22:32:32] Initializing platform accessory 'Decklights entre'...
[21/12/2020, 22:32:32] Initializing platform accessory 'Mattias sänglampa'...
[21/12/2020, 22:32:32] Initializing platform accessory 'Lejas fönster'...
[21/12/2020, 22:32:32] Initializing platform accessory 'Köks lampor'...
[21/12/2020, 22:32:32] Initializing platform accessory 'Hall lampa'...
[21/12/2020, 22:32:32] Initializing platform accessory 'Gästrum'...
[21/12/2020, 22:32:32] Initializing platform accessory 'Garage spotlights'...
[21/12/2020, 22:32:32] Initializing platform accessory 'Garage belysning'...
[21/12/2020, 22:32:32] Initializing platform accessory 'Entretak grov'...
[21/12/2020, 22:32:32] Initializing platform accessory 'Entretak fin'...
[21/12/2020, 22:32:32] Initializing platform accessory 'Buttkickers'...
[21/12/2020, 22:32:32] Initializing platform accessory 'Räcke ledstrip'...
[21/12/2020, 22:32:32] [Telldus Liv!e] [Räcke ledstrip] Your device (model goobay:biltema, id 31) is not auto detected from telldus live. Please add the following to your config, under telldus platform (replace MODEL with a valid type, and optionally set manufacturer):
"unknown_accessories": [{ "id": 31, "model": "MODEL", "manufacturer": "unknown" }]
Valid models are: selflearning-switch, codeswitch, selflearning-dimmer, temperature, EA4C, temperaturehumidity, 1A2D, window-covering, switch
[21/12/2020, 22:32:32] Initializing platform accessory 'Vardagsrum'...
[21/12/2020, 22:32:32] Initializing platform accessory 'Utebelysning'...
[21/12/2020, 22:32:32] [Telldus Liv!e] [Utebelysning] Your device (model n/a, id 23) is not auto detected from telldus live. Please add the following to your config, under telldus platform (replace MODEL with a valid type, and optionally set manufacturer):
"unknown_accessories": [{ "id": 23, "model": "MODEL", "manufacturer": "unknown" }]
Valid models are: selflearning-switch, codeswitch, selflearning-dimmer, temperature, EA4C, temperaturehumidity, 1A2D, window-covering, switch
[21/12/2020, 22:32:32] Initializing platform accessory 'Sova'...
[21/12/2020, 22:32:32] [Telldus Liv!e] [Sova] Your device (model n/a, id 24) is not auto detected from telldus live. Please add the following to your config, under telldus platform (replace MODEL with a valid type, and optionally set manufacturer):
"unknown_accessories": [{ "id": 24, "model": "MODEL", "manufacturer": "unknown" }]
Valid models are: selflearning-switch, codeswitch, selflearning-dimmer, temperature, EA4C, temperaturehumidity, 1A2D, window-covering, switch
[21/12/2020, 22:32:32] Initializing platform accessory 'Verisure Alarm'...
[21/12/2020, 22:32:32] [Telldus Liv!e] [Verisure Alarm] Your device (model mainunit, id 33) is not auto detected from telldus live. Please add the following to your config, under telldus platform (replace MODEL with a valid type, and optionally set manufacturer):
"unknown_accessories": [{ "id": 33, "model": "MODEL", "manufacturer": "unknown" }]
Valid models are: selflearning-switch, codeswitch, selflearning-dimmer, temperature, EA4C, temperaturehumidity, 1A2D, window-covering, switch
[21/12/2020, 22:32:32] Initializing platform accessory 'Nexa z-dimmer'...
[21/12/2020, 22:32:32] [Telldus Liv!e] [Nexa z-dimmer] Your device (model 0060-0003-0003, id 27) is not auto detected from telldus live. Please add the following to your config, under telldus platform (replace MODEL with a valid type, and optionally set manufacturer):
"unknown_accessories": [{ "id": 27, "model": "MODEL", "manufacturer": "unknown" }]
Valid models are: selflearning-switch, codeswitch, selflearning-dimmer, temperature, EA4C, temperaturehumidity, 1A2D, window-covering, switch
[21/12/2020, 22:32:32] Initializing platform accessory 'Lejas taklampa'...
[21/12/2020, 22:32:32] [Telldus Liv!e] [Lejas taklampa] Your device (model 0159-0001-0051, id 29) is not auto detected from telldus live. Please add the following to your config, under telldus platform (replace MODEL with a valid type, and optionally set manufacturer):
"unknown_accessories": [{ "id": 29, "model": "MODEL", "manufacturer": "unknown" }]
Valid models are: selflearning-switch, codeswitch, selflearning-dimmer, temperature, EA4C, temperaturehumidity, 1A2D, window-covering, switch
[21/12/2020, 22:32:32] [Telldus Liv!e] Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 15666576-599e-43f1-840c-af3d64e935df
(node:1070) UnhandledPromiseRejectionWarning: Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 15666576-599e-43f1-840c-af3d64e935df
    at Bridge.Accessory._this.addBridgedAccessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:416:15)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:430:25
    at Array.forEach (<anonymous>)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:417:21
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:10:18
    at /usr/local/lib/node_modules/homebridge-telldus/index.js:142:6
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1070) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1070) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[21/12/2020, 22:33:31] [Homebridge UI] Starting terminal session
[21/12/2020, 22:33:59] [Homebridge UI] Terminal session ended.

**Comment by Mattiasfoto** [comment]
My configuration:

"unknown_accessories": [
                    {
                        "local_id": 29,
                        "type": "device",
                        "model": "selflearning-dimmer",
                        "name": "lejalampa"
                    },
                    {
                        "local_id": 29,
                        "model": "temperature"
                    },
                    {
                        "local_id": 32,
                        "type": "device",
                        "model": "selflearning-dimmer",
                        "name": "test1"
                    },
                    {
                        "local_id": 32,
                        "model": "temperature"
                    },
                    {
                        "local_id": 38,
                        "type": "device",
                        "model": "switch",
                        "name": "test2"
                    },
                    {
                        "local_id": 38,
                        "model": "temperature"
                    },
                    {
                        "local_id": 40,
                        "type": "device",
                        "model": "switch",
                        "name": "test3"
                    },
                    {
                        "local_id": 40,
                        "model": "temperature"
                    },
                    {
                        "local_id": 41,
                        "type": "device",
                        "model": "selflearning-dimmer",
                        "name": "test4"
                    },
                    {
                        "local_id": 41,
                        "model": "temperature"
                    },
                    {
                        "local_id": 50,
                        "type": "device",
                        "model": "switch",
                        "name": "garage status"
                    },
                    {
                        "local_id": 50,
                        "model": "temperature"
                    },
                    {
                        "local_id": 31,
                        "type": "device",
                        "model": "switch"
                    },
                    {
                        "local_id": 23,
                        "disabled": true
                    },
                    {
                        "local_id": 32,
                        "type": "device",
                        "model": "selflearning-dimmer",
                        "name": "test5"
                    },
                    {
                        "local_id": 32,
                        "model": "temperature"
                    },
                    {
                        "local_id": 24,
                        "disabled": true
                    },
                    {
                        "local_id": 33,
                        "disabled": true
                    },
                    {
                        "local_id": 27,
                        "type": "selflearning-dimmer",
                        "name": "Nexa z-dimmer"

**Comment by mifi** [comment]
Hi. did you mange to make i twork? I think you need to add the missing id's (not local_id)

**Comment by Mattiasfoto** [comment]
> Hi. did you mange to make i twork? I think you need to add the missing id's (not local_id)

Hi! No i did not.. I found Home Assistant instead and that works flawless. Thanks anyway!
