### ISSUE TITLE
Cannot add a bridged Accessory with the same UUID as another bridged Accessory

### ISSUE THREAD

**Issue by KyrreP** [johnlemonse/homebridge-telldus#89]
The Telldus plugin has worked perfectly for a year, when I suddenly receive this message. It has happened twice before, and the problem the was solved after creating a new Homebridge for other reasons.
How can I remove the other bridged Acessory?
[Telldus] Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 3e78e8df-fc11-4df3-bc4e-1dda87b3bba4
(node:854) UnhandledPromiseRejectionWarning: Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 3e78e8df-fc11-4df3-bc4e-1dda87b3bba4
    at Bridge.Accessory.addBridgedAccessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:564:15)
    at /usr/local/lib/node_modules/homebridge/src/bridgeService.ts:547:25
    at Array.forEach (<anonymous>)
    at /usr/local/lib/node_modules/homebridge/src/bridgeService.ts:534:21
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:9:18
    at /homebridge/node_modules/homebridge-telldus/index.js:142:6
(Use `node --trace-warnings ...` to show where the warning was created)
(node:854) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:854) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by mifi** [comment]
does faq suggestion help?

**Comment by KyrreP** [comment]
No, I had already studied the faq carefully on beforehand.
I found after trial and error, that a Telldus beta plugin "Import Eliq energy data into Telldus Live!" had to be hidden from Homebridge. Thank you for a very fine Homebridge plugin!
